vich_uploader:
    db_driver: orm

    mappings:
        competences:
            uri_prefix: '%competences_img%'
            upload_destination: '%kernel.project_dir%/public%competences_img%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer